# Generated by Django 5.1 on 2024-09-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
